version: "3.7"

services:
  xml-validate-react-ui:
    container_name: xml-validate-react-ui
    image: xml-validate-react-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:80
